using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TheAirBlow.Stateful.Generators;

/// <summary>
/// Generates <c>UpdateHandler</c> wrappers for Telegram.Bot's client methods
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class WrapperGenerator : IIncrementalGenerator {
    /// <summary>
    /// Type that holds Telegram.Bot's client methods
    /// </summary>
    private const string _extensions = "Telegram.Bot.TelegramBotClientExtensions";
    
    /// <summary>
    /// Chat ID type
    /// </summary>
    private const string _chatIdType = "Telegram.Bot.Types.ChatId";
    
    /// <summary>
    /// Parse mode type, which defaults to Markdown in wrappers
    /// </summary>
    private const string _parseModeType = "Telegram.Bot.Types.Enums.ParseMode";
    
    /// <summary>
    /// Message type, whose state is stored when sent or edited
    /// </summary>
    private const string _messageType = "Telegram.Bot.Types.Message";

    /// <summary>
    /// Names of Telegram.Bot methods to wrap
    /// </summary>
    private static readonly string[] _methods = [
        "SendMessage", "SendPhoto", "SendAudio", "SendDocument", "SendVideo", "SendAnimation",
        "SendVoice", "SendVideoNote", "SendPaidMedia", "SendMediaGroup", "SendLocation", "SendVenue",
        "SendContact", "SendPoll", "SendDice", "SendChatAction", "SendSticker", "SendGift",
        "SendInvoice", "SendGame", "EditMessageText", "EditMessageCaption", "EditMessageMedia",
        "EditMessageReplyMarkup"
    ];

    /// <summary>
    /// Type display format: fully qualified, with nullable annotations
    /// </summary>
    private static readonly SymbolDisplayFormat _typeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.UseSpecialTypes
                                  | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
                                  | SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var docs = context.AdditionalTextsProvider
            .Where(static x => Path.GetFileName(x.Path) == "Telegram.Bot.xml")
            .Select(static (x, token) => x.GetText(token)?.ToString())
            .Collect();
        var source = context.CompilationProvider.Combine(docs)
            .Select(static (pair, token) => Generate(pair.Left, pair.Right, token));
        context.RegisterSourceOutput(source, static (output, text) => {
            if (text != null) output.AddSource("UpdateHandler.API.g.cs", text);
        });
    }

    /// <summary>
    /// Generates the wrapper source
    /// </summary>
    /// <param name="compilation">Compilation</param>
    /// <param name="xml">Contents of Telegram.Bot.xml</param>
    /// <param name="token">Cancellation token</param>
    /// <returns>Source, null if Telegram.Bot is not referenced</returns>
    private static string? Generate(Compilation compilation, ImmutableArray<string?> xml, CancellationToken token) {
        var extensions = compilation.GetTypeByMetadataName(_extensions);
        if (extensions == null) return null;
        var docs = new Dictionary<string, XElement>();
        foreach (var text in xml.Where(x => !string.IsNullOrEmpty(x)))
            foreach (var member in XDocument.Parse(text!).Descendants("member"))
                docs[(string?)member.Attribute("name") ?? ""] = member;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591, CS1573, CS1574, CS1584, CS1658");
        sb.AppendLine();
        sb.AppendLine("namespace TheAirBlow.Stateful;");
        sb.AppendLine();
        sb.AppendLine("public partial class UpdateHandler {");
        foreach (var name in _methods) {
            var methods = extensions.GetMembers(name).OfType<IMethodSymbol>()
                .Where(x => x.IsExtensionMethod && x.Parameters.Length > 1
                            && x.Parameters[1].Type.ToDisplayString() == _chatIdType);
            foreach (var method in methods) {
                token.ThrowIfCancellationRequested();
                Wrapper(sb, method, name == "EditMessageText" ? "EditMessage" : name, docs);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Writes a wrapper for a Telegram.Bot method
    /// </summary>
    /// <param name="sb">String builder</param>
    /// <param name="method">Telegram.Bot method</param>
    /// <param name="name">Wrapper name</param>
    /// <param name="docs">Documentation of Telegram.Bot members</param>
    private static void Wrapper(StringBuilder sb, IMethodSymbol method, string name, Dictionary<string, XElement> docs) {
        var ps = method.Parameters.Skip(1).ToList();
        var chat = ps.First(x => x.Name == "chatId");
        var message = ps.FirstOrDefault(x => x.Name == "messageId");
        var markup = ps.FirstOrDefault(x => x.Name == "replyMarkup");
        var edit = message != null;

        var returnType = ((INamedTypeSymbol)method.ReturnType).TypeArguments.FirstOrDefault();
        var isMessage = returnType?.ToDisplayString() == _messageType;
        var isMessages = returnType is IArrayTypeSymbol array && array.ElementType.ToDisplayString() == _messageType;
        var result = !isMessage && !isMessages ? "global::System.Threading.Tasks.Task"
            : edit ? "global::System.Threading.Tasks.Task<global::Telegram.Bot.Types.Message?>"
            : "global::System.Threading.Tasks.Task<" + returnType!.ToDisplayString(_typeFormat) + ">";
        
        var ordered = new List<IParameterSymbol>();
        ordered.AddRange(ps.Where(x => !x.HasExplicitDefaultValue && !Special(x)));
        if (markup != null) ordered.Add(markup);
        ordered.Add(chat);
        if (message != null) ordered.Add(message);
        ordered.AddRange(ps.Where(x => x.HasExplicitDefaultValue && !Special(x)));

        if (docs.TryGetValue(method.GetDocumentationCommentId() ?? "", out var doc))
            Docs(sb, doc, ps, edit);
        sb.AppendLine($"    public async {result} {name}(");
        for (var i = 0; i < ordered.Count; i++)
            sb.AppendLine($"        {Parameter(ordered[i])}{(i + 1 < ordered.Count ? "," : "")}");
        sb.AppendLine("    ) {");
        sb.AppendLine("        chatId ??= ChatId;");
        sb.AppendLine("        if (chatId == null) throw new global::System.ArgumentNullException(nameof(chatId), \"Failed to infer chat ID\");");
        if (message != null) {
            sb.AppendLine("        messageId ??= MessageId;");
            sb.AppendLine("        if (messageId == null) throw new global::System.ArgumentNullException(nameof(messageId), \"Failed to infer message ID\");");
        }

        var args = string.Join(", ", ps.Select(x => x.Name == "messageId" ? "messageId: messageId.Value" : $"{Identifier(x.Name)}: {Identifier(x.Name)}"));
        var call = $"global::{_extensions}.{method.Name}(Client, {args})";
        var sent = isMessage || isMessages;
        var body = sent ? $"var msg = await {call}.PutState(this);" : $"await {call};";
        if (edit && sent) {
            sb.AppendLine("        try {");
            sb.AppendLine($"            {body}");
            sb.AppendLine("            return msg;");
            sb.AppendLine("        } catch (global::Telegram.Bot.Exceptions.ApiRequestException e) {");
            sb.AppendLine("            if (e.Message.Contains(\"message is not modified\"))");
            sb.AppendLine("                return null;");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");
        } else {
            sb.AppendLine($"        {body}");
            if (sent) sb.AppendLine("        return msg;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Checks if a parameter is inferred or moved in front of the others
    /// </summary>
    /// <param name="p">Parameter</param>
    /// <returns>True if special</returns>
    private static bool Special(IParameterSymbol p) => p.Name is "chatId" or "messageId" or "replyMarkup";

    /// <summary>
    /// Returns the declaration of a wrapper parameter
    /// </summary>
    /// <param name="p">Parameter</param>
    /// <returns>Declaration</returns>
    private static string Parameter(IParameterSymbol p) {
        var inferred = p.Name is "chatId" or "messageId";
        var type = p.Type.ToDisplayString(_typeFormat);
        if (inferred && !type.EndsWith("?")) type += "?";
        if (!p.HasExplicitDefaultValue && !inferred) return $"{type} {Identifier(p.Name)}";
        return $"{type} {Identifier(p.Name)} = {(inferred ? "default" : Default(p))}";
    }

    /// <summary>
    /// Returns the default value of a parameter, Markdown for parse modes
    /// </summary>
    /// <param name="p">Parameter</param>
    /// <returns>C# expression</returns>
    private static string Default(IParameterSymbol p) {
        if (p.Type.ToDisplayString() == _parseModeType) return $"global::{_parseModeType}.Markdown";
        switch (p.ExplicitDefaultValue) {
            case null: return "default";
            case bool b: return b ? "true" : "default";
            case string s: return "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }

        if (p.Type.TypeKind == TypeKind.Enum) {
            var member = p.Type.GetMembers().OfType<IFieldSymbol>()
                .FirstOrDefault(x => x.HasConstantValue && Equals(x.ConstantValue, p.ExplicitDefaultValue));
            return member == null ? $"({p.Type.ToDisplayString(_typeFormat)}){p.ExplicitDefaultValue}"
                : $"{p.Type.ToDisplayString(_typeFormat)}.{member.Name}";
        }

        var text = Convert.ToString(p.ExplicitDefaultValue, CultureInfo.InvariantCulture)!;
        return text is "0" or "0.0" ? "default" : text;
    }

    /// <summary>
    /// Escapes the name if it is a keyword
    /// </summary>
    /// <param name="name">Name</param>
    /// <returns>Identifier</returns>
    private static string Identifier(string name)
        => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    /// <summary>
    /// Writes the documentation of a Telegram.Bot method for its wrapper
    /// </summary>
    /// <param name="sb">String builder</param>
    /// <param name="root">Documentation of the method</param>
    /// <param name="ps">Parameters</param>
    /// <param name="edit">Is this an edit method</param>
    private static void Docs(StringBuilder sb, XElement root, List<IParameterSymbol> ps, bool edit) {
        void Element(string tag, string? attribute = null, string? note = null) {
            var element = root.Elements(tag).FirstOrDefault(x => attribute == null || (string?)x.Attribute("name") == attribute);
            if (element == null) return;
            var open = attribute == null ? tag : $"{tag} name=\"{attribute}\"";
            var inner = string.Concat(element.Nodes().Select(x => x.ToString())).Trim();
            if (note != null) inner += (inner.EndsWith(".") ? " " : ". ") + note;
            var lines = inner.Split('\n').Select(x => x.Trim()).Where(x => x.Length > 0).ToList();
            if (lines.Count == 1) {
                sb.AppendLine($"    /// <{open}>{lines[0]}</{tag}>");
                return;
            }

            sb.AppendLine($"    /// <{open}>");
            foreach (var line in lines) sb.AppendLine($"    /// {line}");
            sb.AppendLine($"    /// </{tag}>");
        }

        Element("summary");
        foreach (var p in ps)
            Element("param", p.Name, p.Name is "chatId" or "messageId" ? "Taken from the handled update if not specified." : null);
        if (edit) {
            sb.AppendLine("    /// <returns>The edited message, null if it was not modified.</returns>");
            return;
        }

        Element("returns");
    }
}
