on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: dotnet build --configuration Release
      - name: Package
        run: dotnet pack --configuration Release --output .
      - name: Publish
        run: |
          dotnet nuget push "*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
